### ISSUE TITLE
running without service_account_key cause error

### ISSUE THREAD

**Issue by andersliland** [kolonialno/velo-action#120]
Running 

```
      - name: Generate version
        uses: kolonialno/velo-action@v1.0.1
        id: velo
````
it used to generate version.

Currently there is a but that provides this error when doing so.

```
/usr/bin/docker run --name europedockerpkgdevnubehubdockerpublicveloaction101_571cfe --label 294b31 --workdir /github/workspace --rm -e IMAGE -e deploy_project_slug -e INPUT_CREATE_RELEASE -e INPUT_DEPLOY_TO_ENVIRONMENTS -e INPUT_LOG_LEVEL -e INPUT_OCTOPUS_API_KEY_SECRET -e INPUT_OCTOPUS_SERVER_SECRET -e INPUT_SERVICE_ACCOUNT_KEY -e INPUT_TENANTS -e INPUT_VELO_ARTIFACT_BUCKET_SECRET -e INPUT_VERSION -e INPUT_WAIT_FOR_SUCCESS_SECONDS -e INPUT_WAIT_FOR_DEPLOYMENT -e INPUT_WORKSPACE -e INPUT_TOKEN -e INPUT_PRECEDING_RUN_IDS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/centro/centro":"/github/workspace" europe-docker.pkg.dev/nube-hub/docker-public/velo-action:1.0.1  "None" "False" "None" "" "False" "None" "velo_action_octopus_server" "velo_action_octopus_api_key" "velo_action_artifacts_bucket_name" "***" ""
[20](https://github.com/kolonialno/centro/runs/6173859898?check_suite_focus=true#step:5:20)22-04-26 10:27:54 Starting trace failed: OTEL_TEMPO_PASSWORD environment variable not set. Traces cannot be send without password.
2022-04-26 10:27:54 Using local credentials.
Traceback (most recent call last):
  File "/app/velo_action/gcp.py", line 35, in _get_secrets_client
    secrets_client = secretmanager.SecretManagerServiceClient(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 465, in __init__
    self._transport = Transport(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/transports/grpc.py", line 158, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/transports/base.py", line 109, in __init__
    credentials, _ = google.auth.default(
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 575, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/velo_action/main.py", line 168, in <module>
    action(s, gh)
  File "/app/velo_action/main.py", line 60, in action
    octopus_server = gcloud.lookup_data(args.octopus_server_secret, args.velo_project)
  File "/app/velo_action/gcp.py", line 71, in lookup_data
    secrets_client = self._get_secrets_client()
  File "/app/velo_action/gcp.py", line [39](https://github.com/kolonialno/centro/runs/6173859898?check_suite_focus=true#step:5:39), in _get_secrets_client
    raise RuntimeError(
RuntimeError: No valid credentials to access Google cloud. Please either specify the INPUT_SERVICE_ACCOUNT_KEY environment or authenticate using 'gcloud auth login'.
```

**Comment by andersliland** [comment]
resolved by https://github.com/kolonialno/velo-action/pull/121
